FROM python:3.11-slim

WORKDIR /app

COPY . .

RUN pip install streamlit duckdb pandas plotly

EXPOSE 8501

CMD ["streamlit", "run", "dashboard/dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]